[package]
name = "reroute"
version = "0.2.4"
authors = ["Garrett Squire <garrettsquire@gmail.com>"]
description = "A router that can use regular expressions for the hyper package"
repository = "https://github.com/gsquire/reroute"
keywords = ["http", "hyper"]
documentation = "https://gsquire.github.io/doc/reroute/reroute"
license = "MIT"

[dependencies]
hyper = { version = "0.9", default-features = false }
regex = "0.1"

[features]
default = ["ssl"]
ssl = ["hyper/ssl"]
serde-serialization = ["hyper/serde-serialization"]
